### ISSUE TITLE
Icons don't show up

### ISSUE THREAD

**Issue by kevinrenskers** [raxityo/BrowserActivity#1]
Hey, nice project. However when including the pod and opening an activity sheet with BrowserActivity.compatibleActivities, the Open in Safari icon is blank.

**Comment by raxityo** [comment]
Thanks for the report, @kevinrenskers and apologies for the delay in response.
Version [`1.1.0`](https://github.com/raxityo/BrowserActivity/releases/tag/1.1.0) fixes the missing icon(s).
